# Site settings
title: docs.k8s.ru на русском языке

description: Собираем материалы по развертыванию приложений с помощью самых современных инструментова автоматизации

keywords: GitOps, DevOps, SRE, Clouds, Linux, Docker, Kubernetes, Git, FluxCD, ArgoCD

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://docs.k8s.ru' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
